---
apiVersion: "kubeflow.org/v1beta1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-imagenet-nccl"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          volumes:
            - name: eastcoastdatasets9-imagenet
              persistentVolumeClaim:
                claimName: eastcoastdatasets9-imagenet
            - name: shm
              emptyDir:
                medium: Memory
                sizeLimit: 2560M
          containers:
            - name: pytorch
              image: posi/k8s-pytorch-test:horovod-mpi-2
              entrypoint: ["mpirun", "-n", "1", "--allow-run-as-root", "python", "/var/imagenet.py"]
              resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - mountPath: /home/jovyan/ecd9
                  name: eastcoastdatasets9-imagenet
                - mountPath: /dev/shm
                  name: shm
              ports:
                - containerPort: 23456 
                  name: dist-url
                  protocol: TCP

    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          volumes:
            - name: eastcoastdatasets9-imagenet
              persistentVolumeClaim:
                claimName: eastcoastdatasets9-imagenet
            - name: shm
              emptyDir:
                medium: Memory
                sizeLimit: 2560M
          containers:
            - name: pytorch
              image: posi/k8s-pytorch-test:horovod-mpi-2
              entrypoint: ["mpirun", "-n", "1", "--allow-run-as-root", "python", "/var/imagenet.py"]
              volumeMounts:
                - mountPath: /home/jovyan/ecd9
                  name: eastcoastdatasets9-imagenet
                - mountPath: /dev/shm
                  name: shm
              resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1
