---
apiVersion: "kubeflow.org/v1beta2"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-imagnet-nccl"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          volumes:
            - name: eastcoastdatasets9-imagenet
              persistentVolumeClaim:
                claimName: eastcoastdatasets9-imagenet
            - name: shm
              emptyDir:
                medium: Memory
                sizeLimit: 2560M
          containers:
            - name: pytorch
              image: posi/k8s-pytorch-test:horovod-mpi-2
              args: [ "--dist-backend", "nccl", "--dist-url", "tcp://127.0.0.1:5000", "-a", "resnet50", "--multiprocessing-distributed" , "--world-size", "2", "--rank", "0" ]
              resources:
                limits:
                nvidia.com/gpu: 4
              volumeMounts:
                - mountPath: /home/jovyan/ecd9
                  name: eastcoastdatasets9-imagenet
                - mountPath: /dev/shm
                  name: shm
              ports:
                - containerPort: 5000
                  name: dist-url
                  protocol: TCP
              env:
                - name: NCCL_SOCKET_IFNAME
                  value: "eth0"
                - name: WORLD_SIZE
                  value: "2"
                - name: RANK
                  value: "0"
                - name: PYTHONUNBUFFERED
                  value: "0"
                #- name: NCCL_LL_THRESHOLD
                #  value: "0"


    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          volumes:
            - name: eastcoastdatasets9-imagenet
              persistentVolumeClaim:
                claimName: eastcoastdatasets9-imagenet
            - name: shm
              emptyDir:
                medium: Memory
                sizeLimit: 2560M
          containers:
            - name: pytorch
              image: posi/k8s-pytorch-test:horovod-mpi-2
              args: [ "--dist-backend", "nccl", "--dist-url", "tcp://pytorch-dist-imagnet-nccl-master-0:5000", "-a", "resnet50", "--multiprocessing-distributed", "--world-size", "2", "--rank", "1" ]
              volumeMounts:
                - mountPath: /home/jovyan/ecd9
                  name: eastcoastdatasets9-imagenet
                - mountPath: /dev/shm
                  name: shm
              resources:
                limits:
                  nvidia.com/gpu: 4
              env:
                - name: NCCL_SOCKET_IFNAME
                  value: "eth0"
                - name: WORLD_SIZE
                  value: "2"
                - name: RANK
                  value: "1"
                - name: PYTHONUNBUFFERED
                  value: "0"
               # - name: NCCL_LL_THRESHOLD
               #   value: "0"
